In [1]:
import GEOparse
import pandas as pd
import numpy as np

gse = GEOparse.get_GEO(
    geo="GSE2034",
    destdir="../data/raw/",
    silent=True,
    how="quick"
)

print(gse)

<SERIES: None - 286 SAMPLES, 0 d(s)>

In [2]:
sample = list(gse.gsms.values())[0]

sample.table.head()

           ID_REF   VALUE ABS_CALL  DETECTION P-VALUE
0  AFFX-BioB-5_at   467.7        P           0.002023
1  AFFX-BioB-M_at   919.8        P           0.000081
2  AFFX-BioB-3_at   468.3        P           0.000195
3  AFFX-BioC-5_at  1371.1        P           0.000127
4  AFFX-BioC-3_at  1048.2        P           0.000070

In [3]:
expression = {}

for sample_id, sample in gse.gsms.items():
    expression[sample_id] = (
        sample.table
        .set_index("ID_REF")["VALUE"]
    )

expression_df = pd.DataFrame(expression)

expression_df.head()

,GSM36777,GSM36778,GSM36779,GSM36780,GSM36781,GSM36782,GSM36783,GSM36784,GSM36785,GSM36786,...,GSM37053,GSM37054,GSM37055,GSM37056,GSM37057,GSM37058,GSM37059,GSM37060,GSM37061,GSM37062
ID_REF,,,,,,,,,,,,,,,,,,,,,
AFFX-BioB-5_at,467.7,754.0,981.4,899.2,730.1,838.5,756.9,1149.3,318.6,473.8,...,2788.0,1557.6,1940.0,1155.8,1428.0,1093.5,882.0,1173.7,879.1,697.1
AFFX-BioB-M_at,919.8,1663.8,2094.1,1733.8,1592.3,1665.9,1717.0,2673.3,738.3,713.9,...,6245.4,4500.7,3753.1,1952.1,2801.6,2159.5,1821.5,2409.3,1771.8,935.6
AFFX-BioB-3_at,468.3,996.3,1029.3,906.8,637.0,907.9,860.2,1174.7,416.7,527.5,...,3683.8,1559.7,2202.0,976.1,1719.6,1063.4,847.4,1413.2,797.1,605.3
AFFX-BioC-5_at,1371.1,2511.1,2699.7,2756.9,2158.4,2023.4,1868.4,2900.1,1403.3,1400.0,...,6572.1,3357.5,4565.8,2959.6,3150.2,2472.3,2106.2,2923.4,1977.3,1932.2
AFFX-BioC-3_at,1048.2,1930.7,1941.4,1658.2,1675.9,1623.3,1842.5,2334.6,986.9,1183.0,...,5708.9,2965.6,3516.3,2074.4,2594.3,1951.8,1754.3,2351.7,1839.1,1329.4

In [4]:
expression_df.shape

(20, 286)